package projetofinal.SistemaInscricaoOficinasMinicursos.entity;


import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "tb_aluno")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Aluno {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Combina com o GENERATED BY DEFAULT AS IDENTITY do Postgres
    private Long id;

    @Column(nullable = false, length = 100)
    private String nome;

    @Column(nullable = false, unique = true, length = 100)
    private String email;

    @Column(nullable = false, unique = true, length = 20)
    private String matricula;
}