# 1. A URL aponta para o seu banco de dados (que está certinho no seu pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/sistemadeinscricaoemoficinaseminicursos

# 2. O USUÁRIO do banco (mude de "sistemadeinscricao..." para "postgres")
spring.datasource.username=postgres

# 3. A SENHA que você definiu ao instalar o PostgreSQL/entrar no pgAdmin
spring.datasource.password=cedep2512

# Configurações do Hibernate/JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true